// Refreshes the gateway snapshot in gateway/ from a checkout of the gateway repository.
//
//   npm run sync:gateway                       # from ../yoon-app
//   YOON_APP_SOURCE=/path/to/yoon-app npm run sync:gateway
//
// Copies exactly GATEWAY_FILES (scripts/gateway.mjs) — the files the build reads — and
// records which gateway commit they came from in gateway/SOURCE.json. Commit the result:
// the website must build from its own repository alone, on any host.
import { execFileSync } from "node:child_process";
import { copyFileSync, existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { GATEWAY_FILES } from "./gateway.mjs";

const source = resolve(process.env.YOON_APP_SOURCE ?? "../yoon-app");
const target = resolve("gateway");

if (!existsSync(join(source, "api/openapi.yaml"))) {
  console.error(
    `[sync-gateway] ${source} does not look like the gateway repository (no api/openapi.yaml).\n` +
      `[sync-gateway] Check it out next to this repository, or set YOON_APP_SOURCE.`,
  );
  process.exit(1);
}

const agentFiles = GATEWAY_FILES.filter((file) => /(^|\/)(CLAUDE|AGENTS)\.md$/i.test(file));
if (agentFiles.length > 0) {
  console.error(
    `[sync-gateway] Refusing to snapshot agent instruction files: ${agentFiles.join(", ")}`,
  );
  process.exit(1);
}

const missing = GATEWAY_FILES.filter((file) => !existsSync(join(source, file)));
if (missing.length > 0) {
  console.error(`[sync-gateway] Missing in ${source}:\n  ${missing.join("\n  ")}`);
  process.exit(1);
}

// Start clean so files the site no longer reads do not linger in the snapshot.
rmSync(target, { recursive: true, force: true });
for (const file of GATEWAY_FILES) {
  mkdirSync(dirname(join(target, file)), { recursive: true });
  copyFileSync(join(source, file), join(target, file));
}

function git(...args) {
  try {
    return execFileSync("git", ["-C", source, ...args], { encoding: "utf8" }).trim();
  } catch {
    return null;
  }
}
const commit = git("rev-parse", "HEAD");
const uncommitted = git("status", "--porcelain", "--", ...GATEWAY_FILES);

// No timestamp: the drift check in CI compares the snapshot, and this file must not
// change when nothing else did.
writeFileSync(
  join(target, "SOURCE.json"),
  JSON.stringify(
    {
      repository: "https://github.com/crossben/yoonpay",
      commit,
      uncommittedChangesInSource: Boolean(uncommitted),
      note: "Generated by `npm run sync:gateway`. Do not edit files in gateway/ by hand.",
    },
    null,
    2,
  ) + "\n",
);

console.log(
  `[sync-gateway] Copied ${GATEWAY_FILES.length} files from ${source}` +
    (commit ? ` @ ${commit.slice(0, 12)}` : "") +
    (uncommitted ? " (including uncommitted changes in the source!)" : "") +
    ` into gateway/.`,
);
